# Generated by Django 4.1 on 2023-06-13 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='table_mappings',
            field=models.JSONField(default=dict, max_length=32768, verbose_name='表映射'),
            preserve_default=False,
        ),
    ]
