# Generated by Django 4.1 on 2023-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_alter_task_table_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table_mappings',
            field=models.JSONField(default=dict, max_length=32768, verbose_name='表映射'),
        ),
    ]
