# Generated by Django 4.1 on 2023-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_alter_task_table_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='ID')),
                ('arn', models.CharField(max_length=255, verbose_name='ARN')),
                ('database', models.CharField(max_length=32, verbose_name='数据库')),
            ],
            options={
                'verbose_name': '端点',
                'verbose_name_plural': '端点',
            },
        ),
    ]
