# Generated by Django 4.1 on 2025-02-20 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0005_table_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplicationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("migration_type", models.CharField(max_length=100)),
                ("recovery_checkpoint", models.CharField(max_length=255)),
                ("replication_instance_arn", models.CharField(max_length=255)),
                ("replication_task_arn", models.CharField(max_length=255)),
                (
                    "replication_task_creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "replication_task_identifier",
                    models.CharField(max_length=255, unique=True),
                ),
                ("replication_task_settings", models.JSONField()),
                (
                    "replication_task_start_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("replication_task_stats", models.JSONField()),
                ("source_endpoint_arn", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("table_mappings", models.JSONField()),
                ("target_endpoint_arn", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "复制任务",
                "verbose_name_plural": "复制任务",
            },
        ),
    ]
