# Generated by Django 4.1 on 2025-02-20 15:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_replicationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicationtask',
            name='replication_task_stats',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
