# Generated by Django 4.1 on 2023-06-13 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
