# Generated by Django 4.1 on 2025-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0008_replicationendpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replicationendpoint",
            name="endpoint_arn",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
