# Generated by Django 4.1 on 2023-06-14 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_endpoint_database_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='database_addr',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='数据库地址'),
            preserve_default=False,
        ),
    ]
