# Generated by Django 4.1 on 2023-06-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_alter_endpoint_database_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='database_addr',
            field=models.CharField(max_length=255, verbose_name='数据库地址'),
        ),
    ]
