# Generated by Django 4.1 on 2023-06-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_alter_endpoint_database_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='database_addr',
            new_name='server_name',
        ),
    ]
