# Generated by Django 4.1 on 2025-02-21 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0012_replicationtask_aws_console_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replicationendpoint",
            options={"verbose_name": "端点", "verbose_name_plural": "端点"},
        ),
    ]
