# Generated by Django 4.1 on 2023-06-14 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_rename_database_addr_endpoint_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='table_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='表名称'),
            preserve_default=False,
        ),
    ]
