# Generated by Django 4.1 on 2023-06-14 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_task_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='arn',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='arn'),
            preserve_default=False,
        ),
    ]
