# Generated by Django 4.1 on 2023-06-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_task_arn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('schema', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '表',
                'verbose_name_plural': '表',
            },
        ),
    ]
