# Generated by Django 4.1 on 2023-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ('identifier', 'database'), 'verbose_name': '端点', 'verbose_name_plural': '端点'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('name',), 'verbose_name': '表', 'verbose_name_plural': '表'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name',), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
