# Generated by Django 4.1 on 2023-06-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redshift", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="identifier",
            field=models.CharField(max_length=128, unique=True, verbose_name="集群"),
        ),
    ]
