# Generated by Django 4.1 on 2023-06-13 05:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreClusterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('is_nofity', models.BooleanField(default=True, verbose_name='是否发送完成通知')),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='redshift.snapshot', verbose_name='快照')),
            ],
            options={
                'verbose_name': '恢复集群任务',
                'verbose_name_plural': '恢复集群任务',
            },
        ),
    ]
