# Generated by Django 4.1 on 2023-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0002_restoreclustertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, verbose_name='集群')),
            ],
            options={
                'verbose_name': '集群',
                'verbose_name_plural': '集群',
            },
        ),
    ]
