# Generated by Django 4.1 on 2023-06-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0003_alter_snapshot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoretabletask',
            name='status',
            field=models.CharField(default='CREATED', max_length=32, verbose_name='状态'),
        ),
    ]
