# Generated by Django 4.1 on 2023-06-14 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0003_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
            preserve_default=False,
        ),
    ]
