# Generated by Django 4.1 on 2023-07-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0005_alter_snapshot_cluster_alter_snapshot_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='create_time_str',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
