# Generated by Django 4.1 on 2023-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0005_alter_snapshot_end_time_alter_snapshot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
