# Generated by Django 4.1 on 2023-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0006_alter_snapshot_end_time_alter_snapshot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
    ]
