# Generated by Django 4.0 on 2023-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0006_alter_snapshot_create_time_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoretabletask',
            name='tables',
            field=models.ManyToManyField(to='redshift.Table', verbose_name='表'),
        ),
    ]
