# Generated by Django 4.1 on 2023-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0007_remove_snapshot_end_time_remove_snapshot_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='identifier',
            field=models.CharField(max_length=128, unique=True, verbose_name='快照'),
        ),
    ]
