# Generated by Django 4.1 on 2023-06-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0008_alter_snapshot_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='identifier',
            field=models.CharField(max_length=128, verbose_name='快照'),
        ),
    ]
