# Generated by Django 4.1 on 2023-06-16 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0009_alter_snapshot_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoreclustertask',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
