# Generated by Django 4.1 on 2023-06-16 12:00

from django.db import migrations, models
import redshift.models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0010_restoreclustertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoreclustertask',
            name='status',
            field=models.CharField(default=redshift.models.RestoreClusterTask.StatusEnum['COMPELETED'], max_length=32, verbose_name='状态'),
        ),
    ]
