# Generated by Django 4.1 on 2023-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redshift', '0012_alter_restoreclustertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoreclustertask',
            name='status',
            field=models.CharField(default='CREATED', max_length=32, verbose_name='状态'),
        ),
    ]
