# Generated by Django 4.1 on 2024-10-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="名称"),
                ),
            ],
            options={
                "verbose_name": "主题",
                "verbose_name_plural": "主题",
            },
        ),
    ]
