# Generated by Django 4.1 on 2024-10-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('name',), 'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
    ]
