# Generated by Django 4.1 on 2024-10-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msk', '0004_topic_event_time_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topn',
            field=models.IntegerField(default=5, verbose_name='TOP N'),
        ),
    ]
