# Generated by Django 4.1 on 2024-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msk', '0005_topic_topn'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_key_out_of_order',
            field=models.BooleanField(default=False, verbose_name='键粒度'),
        ),
    ]
