# Generated by Django 4.1 on 2024-10-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msk', '0006_topic_is_key_out_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='key',
            field=models.CharField(default='id', max_length=128, verbose_name='键'),
        ),
    ]
