# Generated by Django 4.1 on 2024-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msk', '0007_topic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_data',
            field=models.BooleanField(default=False, verbose_name='是否有数据'),
        ),
    ]
