# Generated by Django 4.0 on 2024-08-11 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dynamodb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_rn",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="rn"
            ),
            preserve_default=False,
        ),
    ]
