# Generated by Django 4.0 on 2024-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamodb', '0004_maintransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintransaction',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
