# Generated by Django 4.1 on 2023-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemagenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='CREATED', editable=False, max_length=32, verbose_name='状态'),
        ),
    ]
