# Generated by Django 4.1 on 2023-07-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemagenerator", "0005_task_table_mappings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="table_mappings",
            field=models.JSONField(default=dict, verbose_name="表映射"),
        ),
    ]
