# Generated by Django 4.1 on 2023-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemagenerator', '0006_alter_task_table_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table_mappings',
            field=models.JSONField(editable=False, verbose_name='表映射'),
        ),
    ]
