# Generated by Django 4.1 on 2023-07-08 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schemagenerator", "0007_alter_task_table_mappings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="table_mappings",
        ),
    ]
