# Generated by Django 4.1 on 2023-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemagenerator', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已创建'), (2, '运行中...'), (3, '已完成')], default=1, verbose_name='状态'),
        ),
    ]
