# Generated by Django 4.1 on 2024-10-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemagenerator', '0017_remove_task_enable_vue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
