# Generated by Django 4.0 on 2024-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doris', '0012_alter_s3loadtask_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3loadtask',
            name='bucket_key',
            field=models.CharField(max_length=256, null=True, verbose_name='分桶键'),
        ),
        migrations.AlterField(
            model_name='s3loadtask',
            name='sort_key',
            field=models.CharField(max_length=256, null=True, verbose_name='排序键'),
        ),
    ]
