# Generated by Django 4.0 on 2024-06-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doris', '0013_alter_s3loadtask_bucket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='表'),
        ),
    ]
