# Generated by Django 4.0 on 2024-06-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doris", "0018_s3loadtask_is_create_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3loadtask",
            name="is_load_data",
            field=models.BooleanField(default=False, verbose_name="加载数据"),
        ),
        migrations.AddField(
            model_name="s3loadtask",
            name="is_unload_data",
            field=models.BooleanField(default=False, verbose_name="卸载数据"),
        ),
    ]
