# Generated by Django 4.0 on 2024-07-10 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("doris", "0020_routineload"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineload",
            name="state",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=32, verbose_name="状态"
            ),
            preserve_default=False,
        ),
    ]
